/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ahmed
 */

import Database.*;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.awt.* ;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
public class Loginpage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Loginpage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginpage = new javax.swing.JPanel();
        passwordtext = new javax.swing.JPasswordField();
        usernametxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LOGINBUTTON = new javax.swing.JButton();
        rolechooser = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        userregister = new javax.swing.JLabel();
        emptyfield = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginpage.setBackground(new java.awt.Color(204, 204, 204));
        loginpage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordtext.setBackground(new java.awt.Color(255, 255, 255));
        loginpage.add(passwordtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 166, -1));

        usernametxt.setBackground(new java.awt.Color(255, 255, 255));
        loginpage.add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 166, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("username");
        loginpage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 90, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("password");
        loginpage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, -1));

        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("are you forget you'r password ?");
        loginpage.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        LOGINBUTTON.setText("LOGIN");
        LOGINBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINBUTTONActionPerformed(evt);
            }
        });
        loginpage.add(LOGINBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 91, -1));

        rolechooser.setBackground(new java.awt.Color(255, 255, 255));
        rolechooser.setForeground(new java.awt.Color(0, 0, 0));
        rolechooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MANAGER", "USER" }));
        loginpage.add(rolechooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 166, 38));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Login as");
        loginpage.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        userregister.setForeground(new java.awt.Color(0, 102, 204));
        userregister.setText("you don't have an account ?");
        userregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userregisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userregisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userregisterMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userregisterMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userregisterMouseReleased(evt);
            }
        });
        loginpage.add(userregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        emptyfield.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        emptyfield.setForeground(new java.awt.Color(255, 0, 51));
        loginpage.add(emptyfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 230, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginpage, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGINBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINBUTTONActionPerformed
    String username = usernametxt.getText().trim();
String password = passwordtext.getText().trim();

String chooser = (String) rolechooser.getSelectedItem();

if (username.isEmpty() || password.isEmpty()) {
    emptyfield.setText("Please don't leave any of the fields empty");
} else {
    emptyfield.setText("");
    if (chooser.equals("MANAGER")) {
 
        String fetchedName = Fetching.fetchElementsFromDatabase_with_con("manager", 
                                new String[] {"manager_name"}, new String[] {"manager_id"},password);
        String fetchedID = Fetching.fetchElementsFromDatabase_with_con("manager", 
                                new String[] {"manager_id"}, new String[] {"manager_id"}, password);

        if (fetchedName.contentEquals(username) && fetchedID.contentEquals(password) ) {
            JOptionPane.showMessageDialog(null, "Login successfully");
            this.dispose();
            manager_dashboard ma = new manager_dashboard();
            ma.setLocationRelativeTo(null);
            ma.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "There is an issue either in username or in password. Please recheck and try again.");
        }
    } else {
        if (Fetching.fetchElementsFromDatabase_with_con("users",  
                new String[] {"user_id"}, new String[] {"user_id"}, password).equals(password)
                
                && 
                Fetching.fetchElementsFromDatabase_with_con("users", 
                new String[] {"first_name"}, new String[] {"user_id"}, password).equals(username)
                
                
                ) {
            JOptionPane.showMessageDialog(null, "Login successfully");
        } else {
            JOptionPane.showMessageDialog(null, "There is an issue either in username or in password. Please recheck and try again.");
        }
  }
}

         
        
    }//GEN-LAST:event_LOGINBUTTONActionPerformed

    private void userregisterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userregisterMouseReleased
       
        
    }//GEN-LAST:event_userregisterMouseReleased

    private void userregisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userregisterMouseEntered
        
         userregister.setForeground(Color.blue); 
                userregister.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR)); 
    }//GEN-LAST:event_userregisterMouseEntered

    private void userregisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userregisterMouseExited
      
        userregister.setForeground(new Color(0,102,204));
        userregister.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_userregisterMouseExited

    private void userregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userregisterMouseClicked

        Register usersignup = new Register();
        usersignup.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_userregisterMouseClicked

    private void userregisterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userregisterMousePressed
 ;
       
    }//GEN-LAST:event_userregisterMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOGINBUTTON;
    private javax.swing.JLabel emptyfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel loginpage;
    private javax.swing.JPasswordField passwordtext;
    private javax.swing.JComboBox<String> rolechooser;
    private javax.swing.JTextField usernametxt;
    private javax.swing.JLabel userregister;
    // End of variables declaration//GEN-END:variables
}
