
import Database.Fetching;
import javax.swing.ButtonGroup;
import Database.Record ;
import passengers.* ;
import javax.swing.*;
import javax.swing.text.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ahmed
 */
public class Register extends javax.swing.JFrame {
       String gender = "" ;
       String user_city  = "" ;
       String user_country = "" ;
        int userid = 3 ;
        int address_id = 3 ;

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.setSize(700,300);
        ButtonGroup gendergroupchooser = new ButtonGroup();
        gendergroupchooser.add(gendermale);
        gendergroupchooser.add(genderfemale);
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        first_nametext = new javax.swing.JTextField();
        streetnametext = new javax.swing.JTextField();
        age__text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lastnametext = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        apartmenttext = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nationalitytext = new javax.swing.JComboBox<>();
        countrychooser = new javax.swing.JComboBox<>();
        genderfemale = new javax.swing.JRadioButton();
        gendermale = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        issuetrigger = new javax.swing.JLabel();
        citychooser = new javax.swing.JComboBox<>();
        floornumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        phonenumber1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);
        jPanel2.add(first_nametext);
        first_nametext.setBounds(16, 47, 78, 22);
        jPanel2.add(streetnametext);
        streetnametext.setBounds(400, 50, 78, 22);
        jPanel2.add(age__text);
        age__text.setBounds(20, 120, 78, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("floornumber");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(520, 90, 90, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("FIRST NAME");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 20, 80, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("LAST_NAME");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(140, 20, 80, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("AGE");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 90, 50, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("CITY");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(150, 90, 40, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("nationality");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(400, 90, 70, 16);
        jPanel2.add(lastnametext);
        lastnametext.setBounds(130, 50, 78, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Country");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(270, 20, 60, 16);
        jPanel2.add(apartmenttext);
        apartmenttext.setBounds(270, 120, 80, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("apartment number");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(260, 90, 110, 16);

        nationalitytext.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "American", "British", "French", "German", "Egyptian", "Japanese", "Indian", "Canadian", "Brazilian", "Italian" }));
        jPanel2.add(nationalitytext);
        nationalitytext.setBounds(390, 120, 100, 22);

        countrychooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "United States", "United Kingdom", "France", "Germany", "Egypt", "Japan", "India", "Canada", "Brazil", "Italy" }));
        countrychooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countrychooserActionPerformed(evt);
            }
        });
        jPanel2.add(countrychooser);
        countrychooser.setBounds(250, 50, 110, 22);

        genderfemale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        genderfemale.setForeground(new java.awt.Color(0, 0, 0));
        genderfemale.setText("female");
        genderfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderfemaleActionPerformed(evt);
            }
        });
        jPanel2.add(genderfemale);
        genderfemale.setBounds(20, 200, 98, 21);

        gendermale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gendermale.setForeground(new java.awt.Color(0, 0, 0));
        gendermale.setText("male");
        gendermale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gendermaleActionPerformed(evt);
            }
        });
        jPanel2.add(gendermale);
        gendermale.setBounds(20, 170, 50, 21);

        jButton1.setText("SIGN IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(270, 180, 72, 23);

        issuetrigger.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        issuetrigger.setForeground(new java.awt.Color(204, 0, 51));
        jPanel2.add(issuetrigger);
        issuetrigger.setBounds(110, 220, 370, 20);

        citychooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citychooserActionPerformed(evt);
            }
        });
        jPanel2.add(citychooser);
        citychooser.setBounds(130, 120, 90, 22);

        floornumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floornumberActionPerformed(evt);
            }
        });
        jPanel2.add(floornumber);
        floornumber.setBounds(510, 120, 110, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("street name");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(400, 20, 80, 16);

        phonenumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumber1ActionPerformed(evt);
            }
        });
        jPanel2.add(phonenumber1);
        phonenumber1.setBounds(500, 50, 140, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("phone number");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(520, 20, 90, 16);

        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(backbutton);
        backbutton.setBounds(570, 200, 72, 23);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String first_name = first_nametext.getText().trim();
       String last_name = lastnametext.getText().trim();
       String age = age__text.getText().trim();
       String apartmentnumber = apartmenttext.getText().trim();
       String streetname = streetnametext.getText() ;
       String phonenumberr = floornumber.getText();
       String nationalityuser = (String ) nationalitytext.getSelectedItem();
       String floornumberr = floornumber.getText();
       String city = (String )citychooser.getSelectedItem();
       String country = (String )countrychooser.getSelectedItem();
               
       if (first_name.isEmpty() || last_name.isEmpty() || age.isEmpty() || apartmentnumber.isEmpty() || streetname.isEmpty() || nationalityuser.isEmpty() || floornumberr.isEmpty()){
           issuetrigger.setText("please make sure you filled all the fields ");
       }else {
           String query ="max(user_id)";
           
          String user_idd =  Fetching.fetchElementsFromDatabase_with_con("users", new String [] {query}, new String [] {} );
          userid = Integer.parseInt(user_idd);
           ++userid;     
           
           String addressquery ="max(address_id)";
           String addressid = Fetching.fetchElementsFromDatabase_with_con("address", new String [] {addressquery}, new String [] {} );
          address_id = Integer.parseInt(addressid);
           ++address_id;  
           
           
          String user__id = String.valueOf(userid);
          String add = String.valueOf(address_id);
          
                
            passengerinformation pass  = new passengerinformation(first_name, last_name, age, gender, nationalityuser);
            
            pass.craeteaddress(city, country, streetname, floornumberr, apartmentnumber);
            pass.createcontact(phonenumberr, add);
            
            
            addressinformation addinfo  = new addressinformation();
          Record address_insertion = new Record("address", new String [] {},add ,addinfo.getinformation()  );
          contactinformation connn = new contactinformation();
          Record userinsertion = new Record("users", new String [] {},user__id , pass.getinformation() );
          
       }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void countrychooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countrychooserActionPerformed
           String country = (String) countrychooser.getSelectedItem();
            String city = (String) citychooser.getSelectedItem();
            
           user_country=country;
            user_city = city ;
            
citychooser.removeAllItems();

if (country.equals("Egypt")) {
    
    
    citychooser.addItem("Cairo");
    citychooser.addItem("Alexandria");
    citychooser.addItem("Giza");
    citychooser.addItem("Shubra El Kheima");
    citychooser.addItem("Port Said");
    citychooser.addItem("Suez");
    citychooser.addItem("Luxor");
    citychooser.addItem("Asyut");
    citychooser.addItem("Mansoura");
    citychooser.addItem("Tanta");
    citychooser.addItem("Aswan");
    citychooser.addItem("Faiyum");
    citychooser.addItem("Zagazig");
    citychooser.addItem("Ismailia");
    citychooser.addItem("Damietta");
    citychooser.addItem("Damanhur");
    citychooser.addItem("Beni Suef");
    citychooser.addItem("Hurghada");
    citychooser.addItem("Minya");
    citychooser.addItem("Qena");
    citychooser.addItem("Sohag");

} else if (country.equals("United States")) {
    
    
    
    
    
    
   
    citychooser.addItem("New York");
    citychooser.addItem("Los Angeles");
    citychooser.addItem("Chicago");
    citychooser.addItem("Houston");
    citychooser.addItem("Phoenix");
    citychooser.addItem("Philadelphia");
    citychooser.addItem("San Antonio");
    citychooser.addItem("San Diego");
    citychooser.addItem("Dallas");
    citychooser.addItem("San Jose");

} else if (country.equals("United Kingdom")) {
    
    
    
    
    
    citychooser.addItem("London");
    citychooser.addItem("Birmingham");
    citychooser.addItem("Manchester");
    citychooser.addItem("Glasgow");
    citychooser.addItem("Liverpool");
    citychooser.addItem("Leeds");
    citychooser.addItem("Sheffield");
    citychooser.addItem("Bristol");
    citychooser.addItem("Newcastle");
    citychooser.addItem("Nottingham");

} else if (country.equals("France")) {
    
 
    
    
    citychooser.addItem("Paris");
    citychooser.addItem("Marseille");
    citychooser.addItem("Lyon");
    citychooser.addItem("Toulouse");
    citychooser.addItem("Nice");
    citychooser.addItem("Nantes");
    citychooser.addItem("Strasbourg");
    citychooser.addItem("Montpellier");
    citychooser.addItem("Bordeaux");
    citychooser.addItem("Lille");

} else if (country.equals("Germany")) {
    
     
    
    
    citychooser.addItem("Berlin");
    citychooser.addItem("Hamburg");
    citychooser.addItem("Munich");
    citychooser.addItem("Cologne");
    citychooser.addItem("Frankfurt");
    citychooser.addItem("Stuttgart");
    citychooser.addItem("Düsseldorf");
    citychooser.addItem("Dortmund");
    citychooser.addItem("Essen");
    citychooser.addItem("Leipzig");

} else if (country.equals("Japan")) {
    
       
    
    
    
    citychooser.addItem("Tokyo");
    citychooser.addItem("Osaka");
    citychooser.addItem("Nagoya");
    citychooser.addItem("Sapporo");
    citychooser.addItem("Fukuoka");
    citychooser.addItem("Kobe");
    citychooser.addItem("Kyoto");
    citychooser.addItem("Hiroshima");
    citychooser.addItem("Sendai");
    citychooser.addItem("Yokohama");

} else if (country.equals("India")) {
 
    
    
    citychooser.addItem("Mumbai");
    citychooser.addItem("Delhi");
    citychooser.addItem("Bangalore");
    citychooser.addItem("Hyderabad");
    citychooser.addItem("Ahmedabad");
    citychooser.addItem("Chennai");
    citychooser.addItem("Kolkata");
    citychooser.addItem("Pune");
    citychooser.addItem("Jaipur");
    citychooser.addItem("Lucknow");

} else if (country.equals("Canada")) {
    
    
     
    
    
    citychooser.addItem("Toronto");
    citychooser.addItem("Montreal");
    citychooser.addItem("Vancouver");
    citychooser.addItem("Calgary");
    citychooser.addItem("Ottawa");
    citychooser.addItem("Edmonton");
    citychooser.addItem("Winnipeg");
    citychooser.addItem("Quebec City");
    citychooser.addItem("Hamilton");
    citychooser.addItem("Kitchener");

} else if (country.equals("Brazil")) {
    
    
    
    
    citychooser.addItem("São Paulo");
    citychooser.addItem("Rio de Janeiro");
    citychooser.addItem("Brasília");
    citychooser.addItem("Salvador");
    citychooser.addItem("Fortaleza");
    citychooser.addItem("Belo Horizonte");
    citychooser.addItem("Manaus");
    citychooser.addItem("Curitiba");
    citychooser.addItem("Recife");
    citychooser.addItem("Porto Alegre");

} else if (country.equals("Italy")) {
    
      
    
    citychooser.addItem("Rome");
    citychooser.addItem("Milan");
    citychooser.addItem("Naples");
    citychooser.addItem("Turin");
    citychooser.addItem("Palermo");
    citychooser.addItem("Genoa");
    citychooser.addItem("Bologna");
    citychooser.addItem("Florence");
    citychooser.addItem("Bari");
    citychooser.addItem("Catania");
}

    }//GEN-LAST:event_countrychooserActionPerformed

    private void gendermaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gendermaleActionPerformed
       
        if(gendermale.isSelected()){
            
            gender = "male" ;
                      

        }
    }//GEN-LAST:event_gendermaleActionPerformed

    private void genderfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderfemaleActionPerformed
       if(genderfemale.isSelected()){
            
            gender = "female" ;

        }
       
    }//GEN-LAST:event_genderfemaleActionPerformed

    private void floornumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floornumberActionPerformed
      
     
        
    }//GEN-LAST:event_floornumberActionPerformed

    private void phonenumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumber1ActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        
        Loginpage lo = new Loginpage();
        lo.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void citychooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citychooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citychooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age__text;
    private javax.swing.JTextField apartmenttext;
    private javax.swing.JButton backbutton;
    private javax.swing.JComboBox<String> citychooser;
    private javax.swing.JComboBox<String> countrychooser;
    private javax.swing.JTextField first_nametext;
    private javax.swing.JTextField floornumber;
    private javax.swing.JRadioButton genderfemale;
    private javax.swing.JRadioButton gendermale;
    private javax.swing.JLabel issuetrigger;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastnametext;
    private javax.swing.JComboBox<String> nationalitytext;
    private javax.swing.JTextField phonenumber1;
    private javax.swing.JTextField streetnametext;
    // End of variables declaration//GEN-END:variables
}
